name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ../test_app

      - name: Build
        run: |
          cd build
          cmake --build .

      - name: Test
        run: |
          cd build
          ctest --output-on-failure
